### ISSUE TITLE
How integrate this library in react-native 

### ISSUE THREAD

**Issue by Js-Nanodegree** [tradingview/LightweightChartsIOS#11]

**Comment by makedonsky94** [comment]
Hi! This is wrapper for iOS and its not appliable for react-native
You can use https://github.com/tradingview/lightweight-charts with react-native Webview. You can check the documentation [here](https://github.com/react-native-webview/react-native-webview)
If you need help with integration, open the issue [here](https://github.com/tradingview/lightweight-charts/issues)
