### ISSUE TITLE
Not Able to Format Date in different format in the latest version 3.2.0 

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/LightweightChartsIOS#12]
I have tried to format the date in the latest version no. 3.2.0
Not possible to change the time format from .utc(Double) on the x-Axis
Example for 1 day -- 9:30 AM, 11:05 AM ...
for 1 week -- 19 Jan, 18 Jan, 15 Jan ...
for 1 Month -- Jan20, Dec19 , Nov19 , ...
for 1 year -- Feb2020 , May2020 , Jul2020 ...
for 5 year -- 2020, 2019, 2018 ....

Kindly Suggest

**Comment by makedonsky94** [comment]
Hi! Can you send us an example of code which you using in the project? Looks like there is an issue like you [created before](https://github.com/tradingview/lightweight-charts-android/issues/27)

**Comment by supriyakhankarnw18** [comment]
Yeah sure, 
We are using Swift 5.

let options = ChartOptions(
            layout: LayoutOptions(backgroundColor: "#000000", textColor: "rgba(255, 255, 255, 0.9)"),
            rightPriceScale: VisiblePriceScaleOptions(borderVisible : false, borderColor: "rgba(197, 203, 206, 0.8)"),
            timeScale: TimeScaleOptions(borderVisible: false, borderColor: "rgba(255, 255, 255, 0.5)",timeVisible: true ,secondsVisible: true),
            crosshair: CrosshairOptions(mode: .normal),
            grid: GridOptions(
                verticalLines: GridLineOptions(color: "rgba(227, 227, 227, 0.1)"),
                horizontalLines: GridLineOptions(color: "rgba(227, 227, 227, 0.1)")
            )
        )
For setting chart options
We are using BarData(time: .utc(timestamp: 1611115200) , ...) etc to set chart data.

**Comment by makedonsky94** [comment]
You need to use the `timeFormatter` field in [LocalizationOptions](https://github.com/tradingview/LightweightChartsIOS/blob/master/LightweightCharts/Classes/LightweightChartsModels/Options/ChartOptions/LocalizationOptions.swift)
[DateFormatter](https://developer.apple.com/documentation/foundation/dateformatter) can help you with date customisation

**Comment by gkye** [comment]
Working example below


```swift
  func lightweightChartsDidLoad(_ lightweightCharts: LightweightCharts) {
   // Updates must be made after chart loaded (can't explain why)
    lightweightCharts.timeScale().applyOptions(
      options: TimeScaleOptions(
        tickMarkFormatter: ChartOptions.priceFormatter())
    )
  }

  static func priceFormatter() -> JavaScriptMethod<TickMarkFormatterParameters, String>? {
    let timeFormatter: DateFormatter = {
      let formatter = DateFormatter()
      formatter.dateFormat = "h:mm a"
      return formatter
    }()
    
    let dayOfMonth: DateFormatter = {
      let formatter = DateFormatter()
      formatter.dateFormat = "MM/dd"
      return formatter
    }()
    
    let year: DateFormatter = {
      let formatter = DateFormatter()
      formatter.dateFormat = "yyyy"
      return formatter
    }()
    
    let method: JavaScriptMethod<TickMarkFormatterParameters, String>?
    method = .closure({ (params) -> String in
      print(params.tickMarkType)
      let date = params.time.date() ?? Date()
      switch params.tickMarkType {
      case .timeWithSeconds, .time:
        return timeFormatter.string(from: date)
      case .dayOfMonth, .month:
        return dayOfMonth.string(from: date)
      case .year:
        return year.string(from: date)
      }
    })
    
    return method
  }
  ```
