### ISSUE TITLE
Graph is moving while dragging

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/LightweightChartsIOS#18]
Hi Team,
According to the project requirement, the user should be able to move Crosshair while dragging across the graph. This feature is functioning well. But, when the Crosshair is absent, when the user drags across the graph, it moves which should not be happening. This is the present issue. Is there any solution for the above issue.

https://user-images.githubusercontent.com/70312717/123745835-72740200-d8ce-11eb-8eb5-aade0ff53fdf.mov

**Comment by makedonsky94** [comment]
Hi! You should use [HandleScrollOptions](https://github.com/tradingview/LightweightChartsIOS/blob/master/LightweightCharts/Classes/LightweightChartsModels/Options/ChartOptions/HandleScrollOptions.swift). You can pass it to [handleScroll](https://github.com/tradingview/LightweightChartsIOS/blob/master/LightweightCharts/Classes/LightweightChartsModels/Options/ChartOptions/ChartOptions.swift#L66) field in `applyOptions` method of [ChartApi](https://github.com/tradingview/LightweightChartsIOS/blob/master/LightweightCharts/Classes/Protocols/ChartApi.swift#L114)

**Comment by supriyakhankarnw18** [comment]
Okay, thank you
