### ISSUE TITLE
Graph should not move while Crosshair is absent.

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/LightweightChartsIOS#22]
Hi Team,
According to the project requirement, while Crosshair is present the scroll functionality should work, but it shouldn't scroll when the Crosshair is absent. We have implemented scrolling using "HandleScrollOptions". To remove scrolling while Crosshair is absent, **there should be a method to identify whether the Crosshair is present or not**. Can you please implement this functionality.

**Comment by timocov** [comment]
Created the issue in the upstream project https://github.com/tradingview/lightweight-charts/issues/830
