### ISSUE TITLE
xcode 13.1 ,  No such module 'LightweightCharts'

### ISSUE THREAD

**Issue by amirr4** [tradingview/LightweightChartsIOS#29]

**Comment by timocov** [comment]
@amirr4 could you provide a bit more details what you did? Maybe some logs?

**Comment by lizhao903** [comment]
> 

pod install ,and build ,xcode tip is error ,reason :..../Build/Products/Debug-iphonesimulator/LightweightCharts//lightweight-charts.js: No such file or directory

**Comment by makedonsky94** [comment]
Hi! I've made an update of CocoaPods repository. Can you check the 3.6.2 version?

**Comment by makedonsky94** [comment]
The new version of library is fully available through CocoaPods
