### ISSUE TITLE
Is it possible to make not scrollable chart, but with scrollable crosshair?

### ISSUE THREAD

**Issue by VovaLobanov** [tradingview/LightweightChartsIOS#38]
In the example project there is no the implementation.
Playing around "handleScroll" option doesn't help

**Comment by timocov** [comment]
I believe it is related to https://github.com/tradingview/lightweight-charts/issues/434, which is fixed now and will be available in upcoming release of lightweight-charts. You will be able to disable scrolling/scaling, but tracking mode will work.
