### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by xiaozhuxiong121** [tradingview/LightweightChartsIOS#4]
Does technical analysis charts have an iOS library?

**Comment by timocov** [comment]
> Does technical analysis charts have an iOS library?

Do you mean https://github.com/tradingview/charting_library?

**Comment by xiaozhuxiong121** [comment]
LightweightCharts is written in swift. Is there a swift version of technical analysis charts? How should I use trading view in ios app？

**Comment by timocov** [comment]
> No LightweightCharts is written in swift. 

No, that's not true. This repo is just wrapper for the original `lightweight-charts` library, written in TypeScript and which works in the browser.

**Comment by xiaozhuxiong121** [comment]
> This repo is just wrapper for the original lightweight-charts library

Is there a wrapper `technical analysis charts` library?

![image](https://user-images.githubusercontent.com/7292110/77376706-f0805980-6dab-11ea-97f9-413eacd8e0f4.png)

**Comment by timocov** [comment]
No, we don't have it _yet_. We're working on it, but I can't tell any ETA.
