### ISSUE TITLE
Timeframes supported

### ISSUE THREAD

**Issue by itopstack** [tradingview/LightweightChartsIOS#43]
I have looked into the example code and noticed that it requires the input parameter as string in `yyyy-MM-dd` format only. The value is being used to render axis X (time axis). So, how to display chart in other timeframes rather than day? Which parameters and formats should I send to the library? Thank you.

**Comment by makedonsky94** [comment]
Hi! To send intraday values you can use timestamp. [Here](https://github.com/tradingview/LightweightChartsIOS/blob/master/Example/LightweightCharts/Example/IntradayDataViewController.swift) the example
