### ISSUE TITLE
markers is not display in the demo

### ISSUE THREAD

**Issue by exorxw** [tradingview/LightweightChartsIOS#44]
MarkersViewController set up the markers, but not display in simulator

**Comment by makedonsky94** [comment]
Hi! Thank you for the issue. Seems like there is a bug in async evaluation of settings markers.

**Comment by maikevers** [comment]
Hi all! Is there any workaround for this? Would really like those markers :D

**Comment by exorxw** [comment]
> 

Hi, Is there any progress on this issue?
