### ISSUE TITLE
How to set Series->autoscaleInfoProvider parameter ?

### ISSUE THREAD

**Issue by sanzonejuan** [tradingview/LightweightChartsIOS#49]
I would like to set a proper config value for `AutoscaleInfoProvider` parameter on Series (LineSeries) but I can't find a way to instantiate the object. It doesn't have useful constructors. 👇🏻
<img width="572" alt="image" src="https://user-images.githubusercontent.com/103949275/202930096-ac155e5e-5791-4631-9ba6-2b919620fbba.png">

Inspecting the code I found the following objects but I can't find a way to setup for the series.
<img width="647" alt="image" src="https://user-images.githubusercontent.com/103949275/202930270-e2f93064-8e08-476c-b800-288f744220d2.png">

Any idea or snipped to configure the Line Series prices scale margins? Im using the latest iOS version 3.8

**Comment by pranavladkat** [comment]
can you share how did u solve this issue?
