### ISSUE TITLE
TradingView for Objective-c 

### ISSUE THREAD

**Issue by xiasyu** [tradingview/LightweightChartsIOS#5]
1、Can tradingview be integrated into objective-c developed projects?
2、Can you provide an objective-c demo？

**Comment by timocov** [comment]
@tradingview/lightweight-charts-ios-maintainers can you help with that please?

**Comment by greenJVS** [comment]
@xiasyu The public API of LightweightChartsIOS widely use structures and generics, which can not be used in Objective-C.
The only possible way to integrate LightweightChartsIOS into an Objective-C project is to create a wrapper in swift without structures and generics, just by using NSObject’s subclasses for models and objects. It is a big task, but you can wrap only the features that you need.

**Comment by xiasyu** [comment]
I see,thank you!

**Comment by xiasyu** [comment]
> @xiasyu The public API of LightweightChartsIOS widely use structures and generics, which can not be used in Objective-C.
> 
> The only possible way to integrate LightweightChartsIOS into an Objective-C project is to create a wrapper in swift without structures and generics, just by using NSObject’s subclasses for models and objects. It is a big task, but you can wrap only the features that you need.

Isee,thank you！
