### ISSUE TITLE
applyOptions issue with SwiftUI

### ISSUE THREAD

**Issue by BSC-Spotter** [tradingview/LightweightChartsIOS#64]
import LightweightCharts
let chart = LightweightCharts()
chart.applyOptions(options: ChartOptions(layout: LayoutOptions(backgroundColor: "#111111", textColor: "#FFFFFF")))

The code above used to work, but now it gives the following errors:

Cannot convert value of type 'ChartView.LayoutOptions' (aka '_PlatformViewRepresentableLayoutOptions') to expected argument type 'LayoutOptions?'
Extra argument 'textColor' in call
Initializer 'init(_:)' requires the types '_PlatformViewRepresentableLayoutOptions.Element' (aka '_PlatformViewRepresentableLayoutOptions') and 'String.Element' (aka 'Character') be equivalent

Would apperciate some help with this, again I'm using the library with SwiftUI, on the latest version

**Comment by tfonfara** [comment]
Might be a duplicate of https://github.com/tradingview/LightweightChartsIOS/issues/62, check my suggested workaround there.

**Comment by BSC-Spotter** [comment]
> Might be a duplicate of #62, check my suggested workaround there.

This solution worked
